
import java.io.File;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author io
 */
public class IUPpal extends javax.swing.JFrame {

    String rutaBase = "";
    String estado = "";
    boolean btn1 = false;
    boolean btn2 = false;
    /**
     * Creates new form IUPpal
     */
    public IUPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flcUbicacion = new javax.swing.JFileChooser();
        btnIniciar = new javax.swing.JButton();
        btnP1 = new javax.swing.JButton();
        btnP3 = new javax.swing.JButton();
        btnP2 = new javax.swing.JButton();
        btnP4 = new javax.swing.JButton();
        btnP5 = new javax.swing.JButton();
        btnP6 = new javax.swing.JButton();
        btnP7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEstado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnP1.setText("Punto 1");
        btnP1.setEnabled(false);
        btnP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP1ActionPerformed(evt);
            }
        });

        btnP3.setText("Punto 3");
        btnP3.setEnabled(false);
        btnP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP3ActionPerformed(evt);
            }
        });

        btnP2.setText("Punto 2");
        btnP2.setEnabled(false);
        btnP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2ActionPerformed(evt);
            }
        });

        btnP4.setText("Punto 4");
        btnP4.setEnabled(false);
        btnP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP4ActionPerformed(evt);
            }
        });

        btnP5.setText("Punto 5");
        btnP5.setEnabled(false);
        btnP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP5ActionPerformed(evt);
            }
        });

        btnP6.setText("Punto 6");
        btnP6.setEnabled(false);
        btnP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP6ActionPerformed(evt);
            }
        });

        btnP7.setText("Punto 7");
        btnP7.setEnabled(false);
        btnP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP7ActionPerformed(evt);
            }
        });

        txtEstado.setColumns(20);
        txtEstado.setRows(5);
        jScrollPane1.setViewportView(txtEstado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP4)
                            .addComponent(btnP5)
                            .addComponent(btnP6)
                            .addComponent(btnP7)
                            .addComponent(btnP1)
                            .addComponent(btnP2)
                            .addComponent(btnP3))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnP1)
                        .addGap(4, 4, 4)
                        .addComponent(btnP2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnP4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnP5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnP6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnP7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        flcUbicacion.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = flcUbicacion.showSaveDialog(this);
        
        if (seleccion == flcUbicacion.APPROVE_OPTION) {
            File fichero = flcUbicacion.getSelectedFile();
            rutaBase = fichero.getPath() + "/";
            File base = new File(rutaBase + "base");
            base.mkdir();
            generarArchivosBase();
            btnP1.setEnabled(true);
            btnP2.setEnabled(true);
            btnIniciar.setEnabled(false);
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP4ActionPerformed
        punto4();
    }//GEN-LAST:event_btnP4ActionPerformed

    private void btnP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP1ActionPerformed
        punto1();
        btn1 = true;
        activarBotones();
    }//GEN-LAST:event_btnP1ActionPerformed

    private void btnP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2ActionPerformed
        punto2();
        btn2 = true;
        activarBotones();
    }//GEN-LAST:event_btnP2ActionPerformed

    private void btnP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP3ActionPerformed
        punto3();
    }//GEN-LAST:event_btnP3ActionPerformed

    private void btnP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP5ActionPerformed
        punto5();
    }//GEN-LAST:event_btnP5ActionPerformed

    private void btnP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP6ActionPerformed
        punto6();
    }//GEN-LAST:event_btnP6ActionPerformed

    private void btnP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP7ActionPerformed
        punto7();
    }//GEN-LAST:event_btnP7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPpal().setVisible(true);
            }
        });
    }  

    private void generarArchivosBase() {
        if(AmericaNorte.crearModelo(rutaBase + "base/american.rdf")) {
            mostrar("Creado base/american.rdf");
        }
        if(AmericaCentro.crearModelo(rutaBase + "base/americac.rdf")) {
            mostrar("Creado base/americac.rdf");
        }
        if(AmericaSur.crearModelo(rutaBase + "base/americas.rdf")) {
            mostrar("Creado base/americas.rdf");
        }
    }

    private void punto1() {
        mostrar("**************************");
        File carpeta = new File(rutaBase + "punto1");
        carpeta.mkdir();
        if(Africa.crearModelo(rutaBase + "punto1/africa.rdf")) {
            mostrar("Creado punto1/africa.rdf");
        }
        if(Procesos.Unir3(
                rutaBase + "base/american.rdf", 
                rutaBase + "base/americac.rdf", 
                rutaBase + "base/americas.rdf",
                rutaBase + "punto1/america.rdf")) {
            mostrar("Creado punto1/america.rdf");
        }
        
        if(Asia.crearModelo(rutaBase + "punto1/asia.rdf")) {
            mostrar("Creado punto1/asia.rdf");
        }
        if(Europa.crearModelo(rutaBase + "punto1/europa.rdf")) {
            mostrar("Creado punto1/europa.rdf");
        }
    }

    private void punto2() {  
        mostrar("**************************");
        File carpeta = new File(rutaBase + "punto2");
        carpeta.mkdir();      
        if(Islas.crearModelo(rutaBase + "punto2/islas.rdf")) {
            mostrar("Creado punto2/islas.rdf");
        }       
        if(PrimerMundo.crearModelo(rutaBase + "punto2/primermundo.rdf")) {
            mostrar("Creado punto2/primermundo.rdf");
        }       
        if(TercerMundo.crearModelo(rutaBase + "punto2/tercermundo.rdf")) {
            mostrar("Creado punto2/tercermundo.rdf");
        }
    }

    private void punto3() {
        mostrar("**************************");
        File carpeta = new File(rutaBase + "punto3");
        carpeta.mkdir();
        if(Procesos.Unir7(
                rutaBase + "punto1/africa.rdf", 
                rutaBase + "punto1/america.rdf", 
                rutaBase + "punto1/asia.rdf",
                rutaBase + "punto1/europa.rdf",
                rutaBase + "punto2/islas.rdf",
                rutaBase + "punto2/primermundo.rdf",
                rutaBase + "punto2/tercermundo.rdf",
                rutaBase + "punto3/paisesdetodoelmundo.rdf")) {
            mostrar("Creado punto3/paisesdetodoelmundo.rdf");
        }
    }

    private void punto4() {
        mostrar("**************************");
        File carpeta = new File(rutaBase + "punto4");
        carpeta.mkdir();
        if(Procesos.Intersecar(
                rutaBase + "punto1/america.rdf", 
                rutaBase + "punto2/islas.rdf",
                rutaBase + "punto4/islasamericanas.rdf")) {
            mostrar("Creado punto4/islasamericanas.rdf");
        }
    }

    private void punto5() {
        mostrar("**************************");
        File carpeta = new File(rutaBase + "punto5");
        carpeta.mkdir();
        if(Procesos.Intersecar(
                rutaBase + "punto1/europa.rdf", 
                rutaBase + "punto2/primermundo.rdf",
                rutaBase + "punto5/primermundoeneuropa.rdf")) {
            mostrar("Creado punto5/primermundoeneuropa.rdf");
        }
    }

    private void punto6() {
        mostrar("**************************");
        File carpeta = new File(rutaBase + "punto6");
        carpeta.mkdir();
        if(Procesos.Intersecar(
                rutaBase + "punto2/islas.rdf", 
                rutaBase + "punto2/primermundo.rdf",
                rutaBase + "punto6/islasdeprimermundo.rdf")) {
            mostrar("Creado punto6/islasdeprimermundo.rdf");
        }
    }

    private void punto7() {
        mostrar("**************************");
        File carpeta = new File(rutaBase + "punto7");
        carpeta.mkdir();
        if(Procesos.Intersecar(
                rutaBase + "punto1/asia.rdf", 
                rutaBase + "punto1/europa.rdf",
                rutaBase + "punto7/paiseseuropeosyasiaticos.rdf")) {
            mostrar("Creado punto7/paiseseuropeosyasiaticos.rdf");
        }
    }

    private void mostrar(String cadena) {
        estado = estado + cadena + "\n\n";
        txtEstado.setText(estado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnP1;
    private javax.swing.JButton btnP2;
    private javax.swing.JButton btnP3;
    private javax.swing.JButton btnP4;
    private javax.swing.JButton btnP5;
    private javax.swing.JButton btnP6;
    private javax.swing.JButton btnP7;
    private javax.swing.JFileChooser flcUbicacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtEstado;
    // End of variables declaration//GEN-END:variables

    private void activarBotones() {
        if(btn1 && btn2) {
            btnP3.setEnabled(true);
            btnP4.setEnabled(true);
            btnP5.setEnabled(true);
            btnP6.setEnabled(true);
            btnP7.setEnabled(true);
        }
    }
}
